laguage: go
go:
  - "1.9"
  - "1.10.x"
  - master

go_import_path: github.com/wayt/byt

dist: trusty

sudo: true
services:
  - docker

before_script:
  - go version
  - docker version
  - ls -lha

script:
  - go test -v ./...
  - docker build -t byt .

after_script:
  - docker images

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag byt $DOCKER_USERNAME/byt:latest

deploy:
  provider: script
  script: docker push $DOCKER_USERNAME/byt
  on:
    branch: master

notifications:
  email:
    on_success: change
    on_failure: always
    on_start: false
